Begining Markdown Converison
OWASP/Serverless-Top-10-Project pull request #2
Opened 2018-11-04 22:36 UTC by zachChilders

This adds Intro, ToC, and Injection.  I'll be adding more onto this later today.

2018-11-05 03:11 UTC, Chan9390 commented on 2018/en/0x06-release-notes.md
> +report are mentioned on the ​[Acknowledgements page​](page35).
Page 35 ?

2018-11-05 05:58 UTC, Chan9390 commented on 2018/en/0x0a1-injection.md
> +<image>
Where's the image ?

2018-11-05 21:23 UTC, 4ppsec commented on 2018/en/0x06-release-notes.md
> +report are mentioned on the ​[Acknowledgements page​](page35).
@zachChilders - can you fix the referral to the relevant .md file?

2018-11-05 21:23 UTC, 4ppsec commented on 2018/en/0x0a1-injection.md
> +<image>
@zachChilders - can you add the photos from the /images folder?

2018-11-07 14:18 UTC, 0xbadshah reviewed
Why have you added all the files again ?

2018-11-07 14:20 UTC, 0xbadshah requested changes
**Merging this PR would add duplicate markdown files**. I just realized that the naming convention for the files are of the format `0x0a1-<topic>.md`. I have already added the files with the format `0xa1-<topic>.md`. (according to OWASP Top 10 file naming convention)

Also I see that images are not included in any of the files.

2018-11-11 04:31 UTC, Chan9390 commented on 2018/en/0x00-toc.md
> +[A1:2017 Injection](0x0a1-injection.md)
The file should be `0xa1-injection.md`

2018-11-11 04:33 UTC, Chan9390 commented on 2018/en/0xa1-injection.md
>  ## Serverless Risk Meter
Serverless Risk meter is not required

2018-11-11 04:36 UTC, Chan9390 commented
Currently the images for injection is of the format `0x01injection-<number>.png`. Please change it to `0x01-injection-<number>.png` (with a hyphen separating 0x01 and injection). All other images you have included has followed this naming convention. :+1:

2018-11-11 04:40 UTC, Chan9390 commented
@nu11p0inter I would suggest to squash the commits when merging this PR as there are lots of additions and removals of markdown docs.

2018-11-11 05:26 UTC, zachChilders commented on 2018/en/0x00-toc.md
> +[A1:2017 Injection](0x0a1-injection.md)
good catch

2018-11-11 05:27 UTC, zachChilders commented on 2018/en/0xa1-injection.md
>  ## Serverless Risk Meter
ok

2018-11-11 06:22 UTC, 0xbadshah approved these changes

2018-11-11 20:09 UTC, merged